import fs from 'fs';
import path from 'path';
import { buildCSSVarNameFromToken, flattenTokens } from '../../../../shared/tokens/utils.ts';

export function buildCSSTokens(outPath: string, version: string, tokens: Record<string, any>): void {
    // Ensure the output directory exists
    if (!fs.existsSync(outPath)) {
        fs.mkdirSync(outPath, { recursive: true });
    }

    const builder = (tokenType: string, tokens: any) => {
        const flatt = flattenTokens(tokens, tokenType);
        return flatt.map((token) => `    ${buildCSSVarNameFromToken(token)}: ${token.value};`).join('\n');
    };

    // Write one CSS file per token type
    const generatedFiles: string[] = [];
    Object.entries(tokens).forEach(([tokenType, tokenData]) => {
        const cssHeader = `/* Generated by indeks-tokens v${version} */\n\n:root,:host {\n`;
        const cssBody = builder(tokenType, tokenData);
        const cssFooter = '\n}';
        const cssContent = cssHeader + cssBody + cssFooter;
        const fileName = `${tokenType}.css`;
        fs.writeFileSync(path.join(outPath, fileName), cssContent);
        generatedFiles.push(fileName);
    });

    // Write index.css that imports all generated files and colors.css
    const importLines = [
        ...generatedFiles.map((f) => `@import './${f}';`),
        `@import './themes/sb1.css';`,
        `@import './colors.css';`,
    ];
    fs.writeFileSync(path.join(outPath, 'index.css'), importLines.join('\n'));
}
