import { buildCSSVarNameFromToken, FlatToken, flattenTokens } from '../../../../shared/tokens/utils.ts';
import { themeableDefaults } from '../../../themes/themeables';

/**
 * Genererer Tailwind v4-tema for alt utenom farger. Farger bygges i
 * scripts/build-colors/tailwind.ts, som har det semantiske settet.
 *
 * Blokken er `@theme inline`. Det er ikke kosmetikk: uten `inline` deklarerer Tailwind
 * `--radius-md` og resten på `:root` og regner dem ut der, og da arver barna den
 * utregnede verdien. Med `inline` substitueres verdien inn i selve utility-klassen
 * (`.rounded-md { border-radius: var(--ix-border-radius-md) }`), som resolves per
 * element — nødvendig for at `.ix-dark-mode` og `[data-density]` skal virke lenger ned
 * i treet. Ubrukte `@theme`-nøkler emitter ingenting, så hele settet er gratis.
 */

type Rule = {
    /** Token-path som må matche starten av token.path. */
    match: string[];
    /** Tailwind-navnerom uten prefiks, f.eks. 'radius' gir `--radius-*`. */
    namespace: string;
    /**
     * Emitter literalverdi i stedet for `var()`-alias. Tailwind resolver ikke `var()`,
     * så tokens som havner i en media query må ha verdien inline på byggetid.
     */
    literal?: boolean;
    /** Nøkkel å bruke når token-pathen ikke har segmenter igjen etter `match`. */
    keyWhenExact?: string;
};

const RULES: Rule[] = [
    { match: ['border', 'radius'], namespace: 'radius' },
    { match: ['breakpoint'], namespace: 'breakpoint', literal: true },
    { match: ['font', 'weight'], namespace: 'font-weight' },
    { match: ['transition', 'animation'], namespace: 'ease', keyWhenExact: 'default' },
];

/**
 * `--ix-font-family-normal` mappes til `--font-sans`, ikke `--font-normal`:
 * `.font-normal` finnes allerede i Tailwind som font-weight 400, og ville kollidert.
 */
const FONT_FAMILY_KEYS: Record<string, string> = {
    normal: 'sans',
};

function startsWith(path: string[], prefix: string[]): boolean {
    return prefix.every((segment, i) => path[i] === segment);
}

function findRule(token: FlatToken): { rule: Rule; key: string } | null {
    for (const rule of RULES) {
        if (!startsWith(token.path, rule.match)) continue;

        const rest = token.path.slice(rule.match.length);
        const key = rest.length > 0 ? rest.join('-') : rule.keyWhenExact;
        if (!key) continue;

        return { rule, key };
    }
    return null;
}

/**
 * Tokens fra tokens/*.json. `internal`-tokens (`--ii-`) hoppes over — de er ikke
 * offentlig API og skal ikke eksponeres som Tailwind-utilities.
 */
function mapJsonTokens(tokens: Record<string, any>): Map<string, string> {
    const result = new Map<string, string>();

    Object.entries(tokens).forEach(([tokenType, tokenData]) => {
        flattenTokens(tokenData, tokenType).forEach((token) => {
            if (token.internal) return;

            const match = findRule(token);
            if (!match) return;

            const { rule, key } = match;
            const value = rule.literal ? token.value : `var(${buildCSSVarNameFromToken(token)})`;
            result.set(`--${rule.namespace}-${key}`, value);
        });
    });

    return result;
}

/**
 * Font-family og enkelte font-weights og radiuser finnes bare i themes/themeables.ts,
 * ikke i tokens/*.json — de emitteres av build-colors/web.ts. Vi trenger bare navnene,
 * så defaults er nok: et theme kan overstyre verdien, ikke nøkkelsettet.
 */
function mapThemeableTokens(): Map<string, string> {
    const result = new Map<string, string>();

    Object.keys(themeableDefaults['font-family'] ?? {}).forEach((key) => {
        const namespaceKey = FONT_FAMILY_KEYS[key] ?? key;
        result.set(`--font-${namespaceKey}`, `var(--ix-font-family-${key})`);
    });

    Object.keys(themeableDefaults['font-weight'] ?? {}).forEach((key) => {
        result.set(`--font-weight-${key}`, `var(--ix-font-weight-${key})`);
    });

    Object.keys(themeableDefaults.border?.radius ?? {}).forEach((key) => {
        result.set(`--radius-${key}`, `var(--ix-border-radius-${key})`);
    });

    return result;
}

export function buildTailwindTokens(version: string, tokens: Record<string, any>): string {
    // Samme nøkkel fra begge kilder aliaser til samme --ix-variabel, så en Map holder
    // duplikatene (border.json vs themeables.ts) ute av output.
    const entries = new Map([...mapJsonTokens(tokens), ...mapThemeableTokens()]);

    const lines = [...entries]
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([name, value]) => `    ${name}: ${value};`)
        .join('\n');

    return `/* Generated by indeks-tokens v${version} */\n\n@theme inline {\n${lines}\n}\n`;
}
