packages:
    - 'indeks-tokens'
    - 'indeks-utils'
    - 'indeks-css'
    - 'indeks-react'
    - 'indeks-web'
    - 'indeks-storybook'
    - 'indeks-docs'
    - 'indeks-eksempel'
    - 'shared'

# Sikkerhet: Ikke installer pakker publisert for mindre enn 3 dager siden.
# Beskytter mot supply chain-angrep der ondsinnede versjoner oppdages og fjernes kort tid etter publisering.
# Krever pnpm >= 10.16.0
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
    - '@sb1/*'
trustPolicy: no-downgrad
#trustPolicyExclude:
#trustPolicyIgnoreAfter:

enablePrePostScripts: false
autoInstallPeers: false
strictPeerDependencies: false
preferFrozenLockfile: true
shamefullyHoist: false
#Workspace
link-workspace-packages: true
shared-workspace-lockfile: true
