import path from 'path';
import { writeFileSyncEnsureDir } from '../../../../shared/tokens/utils.ts';
import { flattenTokens, type FlatToken as Token, buildCSSVarNameFromToken } from '../../../../shared/tokens/utils.ts';

// Generate CSS header comment
function generateCSSHeader(version: string): string {
    return `/* Generated by indeks-tokens v${version} */\n\n`;
}

// Build CSS utility classes from tokens
function buildCSSClasses(tokenType: string, tokens: any): string {
    const flattenedTokens = flattenTokens(tokens, tokenType);

    return flattenedTokens
        .filter((token) => !token.internal && token._property)
        .map((token) => buildCSSClass(token))
        .join('\n');
}

// Build a single CSS utility class
function buildCSSClass(token: Token): string {
    const className = `.ix-${token.keyPath.join('-')}`;
    const property = token._property || 'value';
    const varName = buildCSSVarNameFromToken(token);
    return `${className} {\n\t${property}: var(${varName});\n}`;
}

// Generate index.css with all imports
function generateIndexFile(outPath: string, files: string[]): void {
    const imports = files.map((file) => `@import './${file}';`).join('\n');
    writeFileSyncEnsureDir(path.join(outPath, 'index.css'), imports);
}

export function buildCSS(outPath: string, version: string, tokens: Record<string, any>): void {
    const generatedFiles: string[] = ['colors.css'];
    const cssHeader = generateCSSHeader(version);

    // Write one CSS file per token type
    Object.entries(tokens).forEach(([tokenType, tokenData]) => {
        const cssBody = buildCSSClasses(tokenType, tokenData);
        const cssContent = cssHeader + cssBody;
        const fileName = `${tokenType}.css`;

        writeFileSyncEnsureDir(path.join(outPath, fileName), cssContent);
        generatedFiles.push(fileName);
    });

    // Write index.css that imports all generated files
    generateIndexFile(outPath, generatedFiles);
}
