import { readFileSync } from 'fs';
import path from 'path';
import postcss from 'postcss';

/**
 * Genererer Tailwind v4-tema for spacing- og fontstørrelse-skalaene.
 *
 * Disse to skalaene er håndskrevet CSS i denne pakken, ikke tokens i indeks-tokens
 * (spacing varierer med breakpoint og density, fontstørrelse aliaser den interne
 * `--ii-font-size-<n>`-trappen). Derfor leser vi navnene rett ut av kildefilene i stedet
 * for å duplisere en liste her — legger noen til `--ix-spacing-6xl`, dukker `p-6xl` opp
 * av seg selv.
 *
 * `@theme inline` er påkrevd: verdiene endrer seg med `[data-density]` og breakpoint, og
 * uten `inline` ville Tailwind låst dem til det som gjaldt på `:root`.
 */

type Source = {
    /** CSS-fil relativt til pakkeroten. */
    file: string;
    /** Prefiks på Indeks-variabelen som skal plukkes opp. */
    varPrefix: string;
    /** Tailwind-navnerom uten prefiks, f.eks. 'spacing' gir `--spacing-*`. */
    namespace: string;
    /**
     * Følgevariabler Tailwind parrer med nøkkelen, og som må nullstilles.
     * Nøkkelnavnene våre (xs, lg, 3xl …) er de samme som Tailwinds egne, så Tailwinds
     * `--text-lg--line-height` overlever selv om vi overstyrer `--text-lg`. Uten dette
     * får du Indeks' fontstørrelse parret med Tailwinds linjehøyde-ratio, og
     * linjehøyden fra `.ix-body` blir overstyrt.
     */
    resetSuffixes?: string[];
};

const SOURCES: Source[] = [
    { file: 'css/spacing.css', varPrefix: '--ix-spacing-', namespace: 'spacing' },
    {
        file: 'css/typography.css',
        varPrefix: '--ix-font-size-',
        namespace: 'text',
        resetSuffixes: ['--line-height'],
    },
];

/**
 * Plukker ut navnene på custom properties som deklareres i filen. Rekkefølgen fra
 * kildefilen beholdes, siden den følger skalaen (2xs, xs, sm, …) — alfabetisk sortering
 * ville gitt 2xl før 2xs. Duplikater fra density- og breakpoint-blokkene faller bort.
 */
function readScaleKeys(source: Source): string[] {
    const css = readFileSync(path.resolve(source.file), 'utf-8');
    const keys: string[] = [];

    postcss.parse(css).walkDecls((decl) => {
        if (!decl.prop.startsWith(source.varPrefix)) return;

        const key = decl.prop.slice(source.varPrefix.length);
        if (key && !keys.includes(key)) keys.push(key);
    });

    if (keys.length === 0) {
        throw new Error(`Fant ingen ${source.varPrefix}*-variabler i ${source.file}. Er filen flyttet eller endret?`);
    }

    return keys;
}

export function buildTailwindUtils(version: string): string {
    const lines = SOURCES.flatMap((source) =>
        readScaleKeys(source).flatMap((key) => [
            `    --${source.namespace}-${key}: var(${source.varPrefix}${key});`,
            ...(source.resetSuffixes ?? []).map((suffix) => `    --${source.namespace}-${key}${suffix}: initial;`),
        ])
    ).join('\n');

    return `/* Generated by indeks-tokens v${version} */\n\n@theme inline {\n${lines}\n}\n`;
}
